### ISSUE TITLE
移动端关于响应式 设计一个meta头的问题

### ISSUE THREAD

**Issue by Joshua-leyer** [Joshua-leyer/web_project#4]
```css
@viewport {
zoom:1.0;
width: extend-to-zoom;
}
@-ms-viewport {
width: extend-to-zoom;
zoom:1.0;
}
```

```html
<meta name="viewport" content="width=device-width, initial-scale=1">
```
看了半天官网，没看到官网这方面的解释。到底干嘛的

14年的一个youtube的视频。
